# Generated by Django 4.1 on 2022-08-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0003_alter_message_options_topic_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='profile',
        ),
        migrations.AddField(
            model_name='room',
            name='profile',
            field=models.ImageField(default='hello', upload_to='GroupPics'),
            preserve_default=False,
        ),
    ]
