# Generated by Django 4.1 on 2022-08-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0005_alter_room_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile',
            field=models.ImageField(default='cover_img.jpg', null=True, upload_to='GroupPics'),
        ),
    ]
