# Generated by Django 4.1 on 2022-08-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0008_rename_profile_room_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
