# Generated by Django 4.1 on 2022-08-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0011_alter_room_profileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='profileImg',
            new_name='profileimg',
        ),
    ]
