# Generated by Django 4.1 on 2022-08-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0012_rename_profileimg_room_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='profileimg',
        ),
    ]
