# Generated by Django 4.1.1 on 2022-12-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0013_remove_room_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='profileimg',
            field=models.ImageField(default='cover_img.jpg', upload_to='GroupPics'),
        ),
    ]
