# Generated by Django 4.1.1 on 2022-12-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0014_room_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='profileimg',
        ),
    ]
