# Generated by Django 4.1.1 on 2022-12-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupChat', '0016_room_profileimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
