# Generated by Django 4.1.4 on 2023-08-25 15:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(default='cover_img.jpg', max_length=255, verbose_name='image'),
        ),
    ]
